- name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Using the --warn_on_root flag and accepting licenses via SDK manager
          buildozer android debug
        env:
          BUILDOZER_ALLOW_ORG_NAME_START: 1
